#!/bin/sh

branch = $1
test -z $branch && echo "Need to provide a new branch name." 1>&2 && exit 1

if [[ $branch != *"hotfix-"* ]]
then
  branch = "hotfix-$branch"
fi

git checkout -b $branch develop
git commit -a -m "Bumped version by $branch"
